import { Resend } from "resend";
import fs from "fs";

const resend = new Resend(process.env.RESEND_API_KEY);

const sendEmail = async (to, company, pdfPath) => {
  try {

    const pdfBuffer = fs.readFileSync(pdfPath);

    await resend.emails.send({
      from: "pariharyajayesh210@gmail.com",
      to,
      subject: `AI Business Audit Report for ${company}`,

      html: `
        <h2>AI Business Audit Report</h2>

        <p>
          Please find attached your personalized
          AI-generated business audit report.
        </p>

        <p>
          Generated by SimplifIQ AI Automation System
        </p>
      `,

      attachments: [
        {
          filename: `${company}_report.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    console.log("Email sent successfully");

  } catch (error) {

    console.log("Email Error:", error);
  }
};

export default sendEmail;